apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmiru-api
spec:
  replicas: 1
  selector:
    # このセレクタでPodを選択する
    matchLabels:
      # deploymentで指定したラベル
      api: chartmiru
  template:
    metadata:
      labels:
        # セレクタと同じ値
        api: chartmiru
    spec:
      containers:
        - image: asia.gcr.io/chartmiru/chartmiru_api
          name: api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code-local-volume
              mountPath: /root/go/src/chartmiru
        - image: asia.gcr.io/chartmiru/nginx
          name: web-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/sites-enabled
        - image: asia.gcr.io/chartmiru/mysql
          name: db
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: mysql-auth
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-local-volume
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /usr/local/etc
      volumes:
        # mount code for dev
        - name: code-local-volume
          hostPath:
            path: /Users/yuichiro.takarada/chartmiru/api.chartmiru
            type: DirectoryOrCreate
        # mount mysql.cnf
        - name: mysql-config-volume
          configMap:
            name: config
            items:
            - key: my.cnf
              path: my.cnf
        # mount db for dev
        - name: mysql-local-volume
          hostPath:
            #must be full pass
            path: /Users/yuichiro.takarada/chartmiru/batch.chartmiru/Database/data
            type: DirectoryOrCreate
        # mount mysql.cnf
        - name: nginx-config-volume
          configMap:
            name: config
            items:
            - key: nginx.conf
              path: default